//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3603
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alading.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alading.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _new {
            get {
                object obj = ResourceManager.GetObject("_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aldbeta {
            get {
                object obj = ResourceManager.GetObject("aldbeta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alden {
            get {
                object obj = ResourceManager.GetObject("alden", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aldwait {
            get {
                object obj = ResourceManager.GetObject("aldwait", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap auth {
            get {
                object obj = ResourceManager.GetObject("auth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bb_fx {
            get {
                object obj = ResourceManager.GetObject("bb_fx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bb_tj {
            get {
                object obj = ResourceManager.GetObject("bb_tj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bz {
            get {
                object obj = ResourceManager.GetObject("bz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 此刻有交易缺货或者部分缺货，不能合并，请检查！ 的本地化字符串。
        /// </summary>
        internal static string CannotConbineNow {
            get {
                return ResourceManager.GetString("CannotConbineNow", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap cg_gy {
            get {
                object obj = ResourceManager.GetObject("cg_gy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cg_tj {
            get {
                object obj = ResourceManager.GetObject("cg_tj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 您是否认真核查了被合并交易的 收货人姓名，收货人所在省、市、区、详细地址以及邮编 的一致性？ 的本地化字符串。
        /// </summary>
        internal static string CheckTidData {
            get {
                return ResourceManager.GetString("CheckTidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并成功 的本地化字符串。
        /// </summary>
        internal static string ConbineSuccess {
            get {
                return ResourceManager.GetString("ConbineSuccess", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cut {
            get {
                object obj = ResourceManager.GetObject("cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cw_lsz {
            get {
                object obj = ResourceManager.GetObject("cw_lsz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap djia {
            get {
                object obj = ResourceManager.GetObject("djia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dp {
            get {
                object obj = ResourceManager.GetObject("dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dpgl {
            get {
                object obj = ResourceManager.GetObject("dpgl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dy {
            get {
                object obj = ResourceManager.GetObject("dy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dy_sz {
            get {
                object obj = ResourceManager.GetObject("dy_sz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap email {
            get {
                object obj = ResourceManager.GetObject("email", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap email_temp {
            get {
                object obj = ResourceManager.GetObject("email_temp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 出错 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap fileSaveAs {
            get {
                object obj = ResourceManager.GetObject("fileSaveAs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fontBold {
            get {
                object obj = ResourceManager.GetObject("fontBold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fontColor {
            get {
                object obj = ResourceManager.GetObject("fontColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fontItalic {
            get {
                object obj = ResourceManager.GetObject("fontItalic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fontUnderline {
            get {
                object obj = ResourceManager.GetObject("fontUnderline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gd {
            get {
                object obj = ResourceManager.GetObject("gd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] GiftGivenSchema {
            get {
                object obj = ResourceManager.GetObject("GiftGivenSchema", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Imformation {
            get {
                return ResourceManager.GetString("Imformation", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap init {
            get {
                object obj = ResourceManager.GetObject("init", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap insertPicture {
            get {
                object obj = ResourceManager.GetObject("insertPicture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 输入不合法，请检查！ 的本地化字符串。
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap kc {
            get {
                object obj = ResourceManager.GetObject("kc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kc_gl {
            get {
                object obj = ResourceManager.GetObject("kc_gl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kc_pd {
            get {
                object obj = ResourceManager.GetObject("kc_pd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kc_zhs {
            get {
                object obj = ResourceManager.GetObject("kc_zhs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kc_zy {
            get {
                object obj = ResourceManager.GetObject("kc_zy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap log {
            get {
                object obj = ResourceManager.GetObject("log", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo32 {
            get {
                object obj = ResourceManager.GetObject("logo32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ModifyOrderSchema {
            get {
                object obj = ResourceManager.GetObject("ModifyOrderSchema", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 没有勾选订单，不能拆分，请检查！ 的本地化字符串。
        /// </summary>
        internal static string NotSelctCanNOtSplit {
            get {
                return ResourceManager.GetString("NotSelctCanNOtSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有勾选订单，返回待确认，请检查！ 的本地化字符串。
        /// </summary>
        internal static string NotSelctOrder {
            get {
                return ResourceManager.GetString("NotSelctOrder", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap order_all {
            get {
                object obj = ResourceManager.GetObject("order_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap order_finished {
            get {
                object obj = ResourceManager.GetObject("order_finished", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap order_notpay {
            get {
                object obj = ResourceManager.GetObject("order_notpay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap order_pay {
            get {
                object obj = ResourceManager.GetObject("order_pay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap order_refund {
            get {
                object obj = ResourceManager.GetObject("order_refund", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] OrderSpiltSchema {
            get {
                object obj = ResourceManager.GetObject("OrderSpiltSchema", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 请退出重选要合并的交易！ 的本地化字符串。
        /// </summary>
        internal static string OutSelectAgain {
            get {
                return ResourceManager.GetString("OutSelectAgain", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap password {
            get {
                object obj = ResourceManager.GetObject("password", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paste {
            get {
                object obj = ResourceManager.GetObject("paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pj {
            get {
                object obj = ResourceManager.GetObject("pj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap plugin {
            get {
                object obj = ResourceManager.GetObject("plugin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap qh {
            get {
                object obj = ResourceManager.GetObject("qh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap queding {
            get {
                object obj = ResourceManager.GetObject("queding", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap redo {
            get {
                object obj = ResourceManager.GetObject("redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功! 的本地化字符串。
        /// </summary>
        internal static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap set {
            get {
                object obj = ResourceManager.GetObject("set", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shopdeleted {
            get {
                object obj = ResourceManager.GetObject("shopdeleted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shopexit {
            get {
                object obj = ResourceManager.GetObject("shopexit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sp {
            get {
                object obj = ResourceManager.GetObject("sp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 拆分量大于了订单量，不能进行拆分，请检查！ 的本地化字符串。
        /// </summary>
        internal static string SplitNumGreater {
            get {
                return ResourceManager.GetString("SplitNumGreater", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap style {
            get {
                object obj = ResourceManager.GetObject("style", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 提交成功 的本地化字符串。
        /// </summary>
        internal static string SummitSuccess {
            get {
                return ResourceManager.GetString("SummitSuccess", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap sz {
            get {
                object obj = ResourceManager.GetObject("sz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tb_bc {
            get {
                object obj = ResourceManager.GetObject("tb_bc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tb_cld {
            get {
                object obj = ResourceManager.GetObject("tb_cld", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tb_cx {
            get {
                object obj = ResourceManager.GetObject("tb_cx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tb_down {
            get {
                object obj = ResourceManager.GetObject("tb_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tb_dy {
            get {
                object obj = ResourceManager.GetObject("tb_dy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tb_dyyl {
            get {
                object obj = ResourceManager.GetObject("tb_dyyl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tb_excel {
            get {
                object obj = ResourceManager.GetObject("tb_excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tb_fj {
            get {
                object obj = ResourceManager.GetObject("tb_fj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tb_order {
            get {
                object obj = ResourceManager.GetObject("tb_order", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tb_refresh {
            get {
                object obj = ResourceManager.GetObject("tb_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tb_sx {
            get {
                object obj = ResourceManager.GetObject("tb_sx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tc {
            get {
                object obj = ResourceManager.GetObject("tc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 请认真核查被合并交易的 交易id 是否一致！ 的本地化字符串。
        /// </summary>
        internal static string TidNotSame {
            get {
                return ResourceManager.GetString("TidNotSame", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap toggleFontBold {
            get {
                object obj = ResourceManager.GetObject("toggleFontBold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] TradeAddSchema {
            get {
                object obj = ResourceManager.GetObject("TradeAddSchema", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TradeStockSchema {
            get {
                object obj = ResourceManager.GetObject("TradeStockSchema", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TripleDESKey {
            get {
                object obj = ResourceManager.GetObject("TripleDESKey", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap users {
            get {
                object obj = ResourceManager.GetObject("users", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wizard_image {
            get {
                object obj = ResourceManager.GetObject("wizard_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xd {
            get {
                object obj = ResourceManager.GetObject("xd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xs_dd {
            get {
                object obj = ResourceManager.GetObject("xs_dd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xs_dz {
            get {
                object obj = ResourceManager.GetObject("xs_dz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xs_fh {
            get {
                object obj = ResourceManager.GetObject("xs_fh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xs_kh {
            get {
                object obj = ResourceManager.GetObject("xs_kh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
