//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// 原始文件名:
// 生成日期: 2010/4/16 20:31:53
namespace Alading.Web.Entity
{
    
    /// <summary>
    /// 架构中不存在 AladingWebEntities 的注释。
    /// </summary>
    public partial class AladingWebEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// 请使用应用程序配置文件的“AladingWebEntities”部分中的连接字符串初始化新 AladingWebEntities 对象。
        /// </summary>
        public AladingWebEntities() : 
                base("name=AladingWebEntities", "AladingWebEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 AladingWebEntities 对象。
        /// </summary>
        public AladingWebEntities(string connectionString) : 
                base(connectionString, "AladingWebEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 AladingWebEntities 对象。
        /// </summary>
        public AladingWebEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "AladingWebEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// 架构中不存在 Area 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Area> Area
        {
            get
            {
                if ((this._Area == null))
                {
                    this._Area = base.CreateQuery<Area>("[Area]");
                }
                return this._Area;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Area> _Area;
        /// <summary>
        /// 架构中不存在 FileUpdate 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<FileUpdate> FileUpdate
        {
            get
            {
                if ((this._FileUpdate == null))
                {
                    this._FileUpdate = base.CreateQuery<FileUpdate>("[FileUpdate]");
                }
                return this._FileUpdate;
            }
        }
        private global::System.Data.Objects.ObjectQuery<FileUpdate> _FileUpdate;
        /// <summary>
        /// 架构中不存在 HelpCat 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<HelpCat> HelpCat
        {
            get
            {
                if ((this._HelpCat == null))
                {
                    this._HelpCat = base.CreateQuery<HelpCat>("[HelpCat]");
                }
                return this._HelpCat;
            }
        }
        private global::System.Data.Objects.ObjectQuery<HelpCat> _HelpCat;
        /// <summary>
        /// 架构中不存在 HelpTopic 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<HelpTopic> HelpTopic
        {
            get
            {
                if ((this._HelpTopic == null))
                {
                    this._HelpTopic = base.CreateQuery<HelpTopic>("[HelpTopic]");
                }
                return this._HelpTopic;
            }
        }
        private global::System.Data.Objects.ObjectQuery<HelpTopic> _HelpTopic;
        /// <summary>
        /// 架构中不存在 News 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<News> News
        {
            get
            {
                if ((this._News == null))
                {
                    this._News = base.CreateQuery<News>("[News]");
                }
                return this._News;
            }
        }
        private global::System.Data.Objects.ObjectQuery<News> _News;
        /// <summary>
        /// 架构中不存在 NewsCat 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<NewsCat> NewsCat
        {
            get
            {
                if ((this._NewsCat == null))
                {
                    this._NewsCat = base.CreateQuery<NewsCat>("[NewsCat]");
                }
                return this._NewsCat;
            }
        }
        private global::System.Data.Objects.ObjectQuery<NewsCat> _NewsCat;
        /// <summary>
        /// 架构中不存在 Shop 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Shop> Shop
        {
            get
            {
                if ((this._Shop == null))
                {
                    this._Shop = base.CreateQuery<Shop>("[Shop]");
                }
                return this._Shop;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Shop> _Shop;
        /// <summary>
        /// 架构中不存在 Update 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Update> Update
        {
            get
            {
                if ((this._Update == null))
                {
                    this._Update = base.CreateQuery<Update>("[Update]");
                }
                return this._Update;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Update> _Update;
        /// <summary>
        /// 架构中不存在 User 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<User> User
        {
            get
            {
                if ((this._User == null))
                {
                    this._User = base.CreateQuery<User>("[User]");
                }
                return this._User;
            }
        }
        private global::System.Data.Objects.ObjectQuery<User> _User;
        /// <summary>
        /// 架构中不存在 Version 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Version> Version
        {
            get
            {
                if ((this._Version == null))
                {
                    this._Version = base.CreateQuery<Version>("[Version]");
                }
                return this._Version;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Version> _Version;
        /// <summary>
        /// 架构中不存在 Area 的注释。
        /// </summary>
        public void AddToArea(Area area)
        {
            base.AddObject("Area", area);
        }
        /// <summary>
        /// 架构中不存在 FileUpdate 的注释。
        /// </summary>
        public void AddToFileUpdate(FileUpdate fileUpdate)
        {
            base.AddObject("FileUpdate", fileUpdate);
        }
        /// <summary>
        /// 架构中不存在 HelpCat 的注释。
        /// </summary>
        public void AddToHelpCat(HelpCat helpCat)
        {
            base.AddObject("HelpCat", helpCat);
        }
        /// <summary>
        /// 架构中不存在 HelpTopic 的注释。
        /// </summary>
        public void AddToHelpTopic(HelpTopic helpTopic)
        {
            base.AddObject("HelpTopic", helpTopic);
        }
        /// <summary>
        /// 架构中不存在 News 的注释。
        /// </summary>
        public void AddToNews(News news)
        {
            base.AddObject("News", news);
        }
        /// <summary>
        /// 架构中不存在 NewsCat 的注释。
        /// </summary>
        public void AddToNewsCat(NewsCat newsCat)
        {
            base.AddObject("NewsCat", newsCat);
        }
        /// <summary>
        /// 架构中不存在 Shop 的注释。
        /// </summary>
        public void AddToShop(Shop shop)
        {
            base.AddObject("Shop", shop);
        }
        /// <summary>
        /// 架构中不存在 Update 的注释。
        /// </summary>
        public void AddToUpdate(Update update)
        {
            base.AddObject("Update", update);
        }
        /// <summary>
        /// 架构中不存在 User 的注释。
        /// </summary>
        public void AddToUser(User user)
        {
            base.AddObject("User", user);
        }
        /// <summary>
        /// 架构中不存在 Version 的注释。
        /// </summary>
        public void AddToVersion(Version version)
        {
            base.AddObject("Version", version);
        }
    }
    /// <summary>
    /// 架构中不存在 AladingWebModel.Area 的注释。
    /// </summary>
    /// <KeyProperties>
    /// AreaID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="AladingWebModel", Name="Area")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Area : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 Area 对象。
        /// </summary>
        /// <param name="areaID">AreaID 的初始值。</param>
        /// <param name="id">id 的初始值。</param>
        /// <param name="name">name 的初始值。</param>
        public static Area CreateArea(int areaID, string id, string name)
        {
            Area area = new Area();
            area.AreaID = areaID;
            area.id = id;
            area.name = name;
            return area;
        }
        /// <summary>
        /// 架构中不存在属性 AreaID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int AreaID
        {
            get
            {
                return this._AreaID;
            }
            set
            {
                this.OnAreaIDChanging(value);
                this.ReportPropertyChanging("AreaID");
                this._AreaID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AreaID");
                this.OnAreaIDChanged();
            }
        }
        private int _AreaID;
        partial void OnAreaIDChanging(int value);
        partial void OnAreaIDChanged();
        /// <summary>
        /// 架构中不存在属性 id 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private string _id;
        partial void OnidChanging(string value);
        partial void OnidChanged();
        /// <summary>
        /// 架构中不存在属性 type 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> type
        {
            get
            {
                return this._type;
            }
            set
            {
                this.OntypeChanging(value);
                this.ReportPropertyChanging("type");
                this._type = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("type");
                this.OntypeChanged();
            }
        }
        private global::System.Nullable<int> _type;
        partial void OntypeChanging(global::System.Nullable<int> value);
        partial void OntypeChanged();
        /// <summary>
        /// 架构中不存在属性 name 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// 架构中不存在属性 parent_id 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string parent_id
        {
            get
            {
                return this._parent_id;
            }
            set
            {
                this.Onparent_idChanging(value);
                this.ReportPropertyChanging("parent_id");
                this._parent_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("parent_id");
                this.Onparent_idChanged();
            }
        }
        private string _parent_id;
        partial void Onparent_idChanging(string value);
        partial void Onparent_idChanged();
        /// <summary>
        /// 架构中不存在属性 zip 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string zip
        {
            get
            {
                return this._zip;
            }
            set
            {
                this.OnzipChanging(value);
                this.ReportPropertyChanging("zip");
                this._zip = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("zip");
                this.OnzipChanged();
            }
        }
        private string _zip;
        partial void OnzipChanging(string value);
        partial void OnzipChanged();
    }
    /// <summary>
    /// 架构中不存在 AladingWebModel.FileUpdate 的注释。
    /// </summary>
    /// <KeyProperties>
    /// UpdateFileID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="AladingWebModel", Name="FileUpdate")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class FileUpdate : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 FileUpdate 对象。
        /// </summary>
        /// <param name="updateFileID">UpdateFileID 的初始值。</param>
        /// <param name="versionCode">VersionCode 的初始值。</param>
        /// <param name="fileName">FileName 的初始值。</param>
        /// <param name="fileNameAlias">FileNameAlias 的初始值。</param>
        /// <param name="filePath">FilePath 的初始值。</param>
        /// <param name="srcFilePath">SrcFilePath 的初始值。</param>
        /// <param name="length">Length 的初始值。</param>
        /// <param name="runAfterUpdate">RunAfterUpdate 的初始值。</param>
        public static FileUpdate CreateFileUpdate(long updateFileID, string versionCode, string fileName, string fileNameAlias, string filePath, string srcFilePath, string length, bool runAfterUpdate)
        {
            FileUpdate fileUpdate = new FileUpdate();
            fileUpdate.UpdateFileID = updateFileID;
            fileUpdate.VersionCode = versionCode;
            fileUpdate.FileName = fileName;
            fileUpdate.FileNameAlias = fileNameAlias;
            fileUpdate.FilePath = filePath;
            fileUpdate.SrcFilePath = srcFilePath;
            fileUpdate.Length = length;
            fileUpdate.RunAfterUpdate = runAfterUpdate;
            return fileUpdate;
        }
        /// <summary>
        /// 架构中不存在属性 UpdateFileID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long UpdateFileID
        {
            get
            {
                return this._UpdateFileID;
            }
            set
            {
                this.OnUpdateFileIDChanging(value);
                this.ReportPropertyChanging("UpdateFileID");
                this._UpdateFileID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UpdateFileID");
                this.OnUpdateFileIDChanged();
            }
        }
        private long _UpdateFileID;
        partial void OnUpdateFileIDChanging(long value);
        partial void OnUpdateFileIDChanged();
        /// <summary>
        /// 架构中不存在属性 VersionCode 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string VersionCode
        {
            get
            {
                return this._VersionCode;
            }
            set
            {
                this.OnVersionCodeChanging(value);
                this.ReportPropertyChanging("VersionCode");
                this._VersionCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("VersionCode");
                this.OnVersionCodeChanged();
            }
        }
        private string _VersionCode;
        partial void OnVersionCodeChanging(string value);
        partial void OnVersionCodeChanged();
        /// <summary>
        /// 架构中不存在属性 FileName 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this._FileName;
            }
            set
            {
                this.OnFileNameChanging(value);
                this.ReportPropertyChanging("FileName");
                this._FileName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("FileName");
                this.OnFileNameChanged();
            }
        }
        private string _FileName;
        partial void OnFileNameChanging(string value);
        partial void OnFileNameChanged();
        /// <summary>
        /// 架构中不存在属性 FileNameAlias 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FileNameAlias
        {
            get
            {
                return this._FileNameAlias;
            }
            set
            {
                this.OnFileNameAliasChanging(value);
                this.ReportPropertyChanging("FileNameAlias");
                this._FileNameAlias = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("FileNameAlias");
                this.OnFileNameAliasChanged();
            }
        }
        private string _FileNameAlias;
        partial void OnFileNameAliasChanging(string value);
        partial void OnFileNameAliasChanged();
        /// <summary>
        /// 架构中不存在属性 FilePath 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FilePath
        {
            get
            {
                return this._FilePath;
            }
            set
            {
                this.OnFilePathChanging(value);
                this.ReportPropertyChanging("FilePath");
                this._FilePath = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("FilePath");
                this.OnFilePathChanged();
            }
        }
        private string _FilePath;
        partial void OnFilePathChanging(string value);
        partial void OnFilePathChanged();
        /// <summary>
        /// 架构中不存在属性 SrcFilePath 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SrcFilePath
        {
            get
            {
                return this._SrcFilePath;
            }
            set
            {
                this.OnSrcFilePathChanging(value);
                this.ReportPropertyChanging("SrcFilePath");
                this._SrcFilePath = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("SrcFilePath");
                this.OnSrcFilePathChanged();
            }
        }
        private string _SrcFilePath;
        partial void OnSrcFilePathChanging(string value);
        partial void OnSrcFilePathChanged();
        /// <summary>
        /// 架构中不存在属性 Length 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Length
        {
            get
            {
                return this._Length;
            }
            set
            {
                this.OnLengthChanging(value);
                this.ReportPropertyChanging("Length");
                this._Length = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Length");
                this.OnLengthChanged();
            }
        }
        private string _Length;
        partial void OnLengthChanging(string value);
        partial void OnLengthChanged();
        /// <summary>
        /// 架构中不存在属性 RunAfterUpdate 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool RunAfterUpdate
        {
            get
            {
                return this._RunAfterUpdate;
            }
            set
            {
                this.OnRunAfterUpdateChanging(value);
                this.ReportPropertyChanging("RunAfterUpdate");
                this._RunAfterUpdate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("RunAfterUpdate");
                this.OnRunAfterUpdateChanged();
            }
        }
        private bool _RunAfterUpdate;
        partial void OnRunAfterUpdateChanging(bool value);
        partial void OnRunAfterUpdateChanged();
        /// <summary>
        /// 架构中不存在属性 Expand1 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Expand1
        {
            get
            {
                return this._Expand1;
            }
            set
            {
                this.OnExpand1Changing(value);
                this.ReportPropertyChanging("Expand1");
                this._Expand1 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Expand1");
                this.OnExpand1Changed();
            }
        }
        private string _Expand1;
        partial void OnExpand1Changing(string value);
        partial void OnExpand1Changed();
        /// <summary>
        /// 架构中不存在属性 Expand2 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Expand2
        {
            get
            {
                return this._Expand2;
            }
            set
            {
                this.OnExpand2Changing(value);
                this.ReportPropertyChanging("Expand2");
                this._Expand2 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Expand2");
                this.OnExpand2Changed();
            }
        }
        private string _Expand2;
        partial void OnExpand2Changing(string value);
        partial void OnExpand2Changed();
    }
    /// <summary>
    /// 架构中不存在 AladingWebModel.HelpCat 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="AladingWebModel", Name="HelpCat")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class HelpCat : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 HelpCat 对象。
        /// </summary>
        /// <param name="id">Id 的初始值。</param>
        /// <param name="name">Name 的初始值。</param>
        public static HelpCat CreateHelpCat(int id, string name)
        {
            HelpCat helpCat = new HelpCat();
            helpCat.Id = id;
            helpCat.Name = name;
            return helpCat;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 Name 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// 架构中不存在属性 Group 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Group
        {
            get
            {
                return this._Group;
            }
            set
            {
                this.OnGroupChanging(value);
                this.ReportPropertyChanging("Group");
                this._Group = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Group");
                this.OnGroupChanged();
            }
        }
        private string _Group;
        partial void OnGroupChanging(string value);
        partial void OnGroupChanged();
    }
    /// <summary>
    /// 架构中不存在 AladingWebModel.HelpTopic 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="AladingWebModel", Name="HelpTopic")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class HelpTopic : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 HelpTopic 对象。
        /// </summary>
        /// <param name="id">Id 的初始值。</param>
        /// <param name="title">Title 的初始值。</param>
        /// <param name="content">Content 的初始值。</param>
        /// <param name="postTime">PostTime 的初始值。</param>
        /// <param name="cat">Cat 的初始值。</param>
        /// <param name="source">Source 的初始值。</param>
        /// <param name="type">Type 的初始值。</param>
        /// <param name="click">Click 的初始值。</param>
        public static HelpTopic CreateHelpTopic(int id, string title, string content, global::System.DateTime postTime, int cat, string source, int type, int click)
        {
            HelpTopic helpTopic = new HelpTopic();
            helpTopic.Id = id;
            helpTopic.Title = title;
            helpTopic.Content = content;
            helpTopic.PostTime = postTime;
            helpTopic.Cat = cat;
            helpTopic.Source = source;
            helpTopic.Type = type;
            helpTopic.Click = click;
            return helpTopic;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 Title 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// 架构中不存在属性 Content 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this._Content;
            }
            set
            {
                this.OnContentChanging(value);
                this.ReportPropertyChanging("Content");
                this._Content = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Content");
                this.OnContentChanged();
            }
        }
        private string _Content;
        partial void OnContentChanging(string value);
        partial void OnContentChanged();
        /// <summary>
        /// 架构中不存在属性 PostTime 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime PostTime
        {
            get
            {
                return this._PostTime;
            }
            set
            {
                this.OnPostTimeChanging(value);
                this.ReportPropertyChanging("PostTime");
                this._PostTime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PostTime");
                this.OnPostTimeChanged();
            }
        }
        private global::System.DateTime _PostTime;
        partial void OnPostTimeChanging(global::System.DateTime value);
        partial void OnPostTimeChanged();
        /// <summary>
        /// 架构中不存在属性 Cat 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Cat
        {
            get
            {
                return this._Cat;
            }
            set
            {
                this.OnCatChanging(value);
                this.ReportPropertyChanging("Cat");
                this._Cat = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Cat");
                this.OnCatChanged();
            }
        }
        private int _Cat;
        partial void OnCatChanging(int value);
        partial void OnCatChanged();
        /// <summary>
        /// 架构中不存在属性 Source 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Source
        {
            get
            {
                return this._Source;
            }
            set
            {
                this.OnSourceChanging(value);
                this.ReportPropertyChanging("Source");
                this._Source = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Source");
                this.OnSourceChanged();
            }
        }
        private string _Source;
        partial void OnSourceChanging(string value);
        partial void OnSourceChanged();
        /// <summary>
        /// 架构中不存在属性 Type 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this.ReportPropertyChanging("Type");
                this._Type = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Type");
                this.OnTypeChanged();
            }
        }
        private int _Type;
        partial void OnTypeChanging(int value);
        partial void OnTypeChanged();
        /// <summary>
        /// 架构中不存在属性 Click 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Click
        {
            get
            {
                return this._Click;
            }
            set
            {
                this.OnClickChanging(value);
                this.ReportPropertyChanging("Click");
                this._Click = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Click");
                this.OnClickChanged();
            }
        }
        private int _Click;
        partial void OnClickChanging(int value);
        partial void OnClickChanged();
    }
    /// <summary>
    /// 架构中不存在 AladingWebModel.News 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="AladingWebModel", Name="News")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class News : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 News 对象。
        /// </summary>
        /// <param name="id">Id 的初始值。</param>
        /// <param name="title">Title 的初始值。</param>
        /// <param name="content">Content 的初始值。</param>
        /// <param name="postTime">PostTime 的初始值。</param>
        /// <param name="cat">Cat 的初始值。</param>
        /// <param name="source">Source 的初始值。</param>
        /// <param name="type">Type 的初始值。</param>
        /// <param name="click">Click 的初始值。</param>
        public static News CreateNews(int id, string title, string content, global::System.DateTime postTime, int cat, string source, int type, int click)
        {
            News news = new News();
            news.Id = id;
            news.Title = title;
            news.Content = content;
            news.PostTime = postTime;
            news.Cat = cat;
            news.Source = source;
            news.Type = type;
            news.Click = click;
            return news;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 Title 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// 架构中不存在属性 Content 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this._Content;
            }
            set
            {
                this.OnContentChanging(value);
                this.ReportPropertyChanging("Content");
                this._Content = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Content");
                this.OnContentChanged();
            }
        }
        private string _Content;
        partial void OnContentChanging(string value);
        partial void OnContentChanged();
        /// <summary>
        /// 架构中不存在属性 PostTime 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime PostTime
        {
            get
            {
                return this._PostTime;
            }
            set
            {
                this.OnPostTimeChanging(value);
                this.ReportPropertyChanging("PostTime");
                this._PostTime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PostTime");
                this.OnPostTimeChanged();
            }
        }
        private global::System.DateTime _PostTime;
        partial void OnPostTimeChanging(global::System.DateTime value);
        partial void OnPostTimeChanged();
        /// <summary>
        /// 架构中不存在属性 Cat 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Cat
        {
            get
            {
                return this._Cat;
            }
            set
            {
                this.OnCatChanging(value);
                this.ReportPropertyChanging("Cat");
                this._Cat = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Cat");
                this.OnCatChanged();
            }
        }
        private int _Cat;
        partial void OnCatChanging(int value);
        partial void OnCatChanged();
        /// <summary>
        /// 架构中不存在属性 Source 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Source
        {
            get
            {
                return this._Source;
            }
            set
            {
                this.OnSourceChanging(value);
                this.ReportPropertyChanging("Source");
                this._Source = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Source");
                this.OnSourceChanged();
            }
        }
        private string _Source;
        partial void OnSourceChanging(string value);
        partial void OnSourceChanged();
        /// <summary>
        /// 架构中不存在属性 Type 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this.ReportPropertyChanging("Type");
                this._Type = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Type");
                this.OnTypeChanged();
            }
        }
        private int _Type;
        partial void OnTypeChanging(int value);
        partial void OnTypeChanged();
        /// <summary>
        /// 架构中不存在属性 Click 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Click
        {
            get
            {
                return this._Click;
            }
            set
            {
                this.OnClickChanging(value);
                this.ReportPropertyChanging("Click");
                this._Click = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Click");
                this.OnClickChanged();
            }
        }
        private int _Click;
        partial void OnClickChanging(int value);
        partial void OnClickChanged();
    }
    /// <summary>
    /// 架构中不存在 AladingWebModel.NewsCat 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="AladingWebModel", Name="NewsCat")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class NewsCat : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 NewsCat 对象。
        /// </summary>
        /// <param name="id">Id 的初始值。</param>
        /// <param name="name">Name 的初始值。</param>
        public static NewsCat CreateNewsCat(int id, string name)
        {
            NewsCat newsCat = new NewsCat();
            newsCat.Id = id;
            newsCat.Name = name;
            return newsCat;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 Name 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// 架构中不存在属性 Group 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Group
        {
            get
            {
                return this._Group;
            }
            set
            {
                this.OnGroupChanging(value);
                this.ReportPropertyChanging("Group");
                this._Group = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Group");
                this.OnGroupChanged();
            }
        }
        private string _Group;
        partial void OnGroupChanging(string value);
        partial void OnGroupChanged();
    }
    /// <summary>
    /// 架构中不存在 AladingWebModel.Shop 的注释。
    /// </summary>
    /// <KeyProperties>
    /// ShopID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="AladingWebModel", Name="Shop")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Shop : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 Shop 对象。
        /// </summary>
        /// <param name="shopID">ShopID 的初始值。</param>
        /// <param name="shopCode">ShopCode 的初始值。</param>
        /// <param name="userCode">UserCode 的初始值。</param>
        /// <param name="shopNick">ShopNick 的初始值。</param>
        /// <param name="shopType">ShopType 的初始值。</param>
        /// <param name="sign">Sign 的初始值。</param>
        public static Shop CreateShop(int shopID, string shopCode, string userCode, string shopNick, int shopType, string sign)
        {
            Shop shop = new Shop();
            shop.ShopID = shopID;
            shop.ShopCode = shopCode;
            shop.UserCode = userCode;
            shop.ShopNick = shopNick;
            shop.ShopType = shopType;
            shop.Sign = sign;
            return shop;
        }
        /// <summary>
        /// 架构中不存在属性 ShopID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ShopID
        {
            get
            {
                return this._ShopID;
            }
            set
            {
                this.OnShopIDChanging(value);
                this.ReportPropertyChanging("ShopID");
                this._ShopID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ShopID");
                this.OnShopIDChanged();
            }
        }
        private int _ShopID;
        partial void OnShopIDChanging(int value);
        partial void OnShopIDChanged();
        /// <summary>
        /// 架构中不存在属性 ShopCode 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ShopCode
        {
            get
            {
                return this._ShopCode;
            }
            set
            {
                this.OnShopCodeChanging(value);
                this.ReportPropertyChanging("ShopCode");
                this._ShopCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ShopCode");
                this.OnShopCodeChanged();
            }
        }
        private string _ShopCode;
        partial void OnShopCodeChanging(string value);
        partial void OnShopCodeChanged();
        /// <summary>
        /// 架构中不存在属性 UserCode 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UserCode
        {
            get
            {
                return this._UserCode;
            }
            set
            {
                this.OnUserCodeChanging(value);
                this.ReportPropertyChanging("UserCode");
                this._UserCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("UserCode");
                this.OnUserCodeChanged();
            }
        }
        private string _UserCode;
        partial void OnUserCodeChanging(string value);
        partial void OnUserCodeChanged();
        /// <summary>
        /// 架构中不存在属性 ShopNick 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ShopNick
        {
            get
            {
                return this._ShopNick;
            }
            set
            {
                this.OnShopNickChanging(value);
                this.ReportPropertyChanging("ShopNick");
                this._ShopNick = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ShopNick");
                this.OnShopNickChanged();
            }
        }
        private string _ShopNick;
        partial void OnShopNickChanging(string value);
        partial void OnShopNickChanged();
        /// <summary>
        /// 架构中不存在属性 ShopType 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ShopType
        {
            get
            {
                return this._ShopType;
            }
            set
            {
                this.OnShopTypeChanging(value);
                this.ReportPropertyChanging("ShopType");
                this._ShopType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ShopType");
                this.OnShopTypeChanged();
            }
        }
        private int _ShopType;
        partial void OnShopTypeChanging(int value);
        partial void OnShopTypeChanged();
        /// <summary>
        /// 架构中不存在属性 ShopTypeName 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ShopTypeName
        {
            get
            {
                return this._ShopTypeName;
            }
            set
            {
                this.OnShopTypeNameChanging(value);
                this.ReportPropertyChanging("ShopTypeName");
                this._ShopTypeName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ShopTypeName");
                this.OnShopTypeNameChanged();
            }
        }
        private string _ShopTypeName;
        partial void OnShopTypeNameChanging(string value);
        partial void OnShopTypeNameChanged();
        /// <summary>
        /// 架构中不存在属性 Sign 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Sign
        {
            get
            {
                return this._Sign;
            }
            set
            {
                this.OnSignChanging(value);
                this.ReportPropertyChanging("Sign");
                this._Sign = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Sign");
                this.OnSignChanged();
            }
        }
        private string _Sign;
        partial void OnSignChanging(string value);
        partial void OnSignChanged();
        /// <summary>
        /// 架构中不存在属性 Province 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Province
        {
            get
            {
                return this._Province;
            }
            set
            {
                this.OnProvinceChanging(value);
                this.ReportPropertyChanging("Province");
                this._Province = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Province");
                this.OnProvinceChanged();
            }
        }
        private string _Province;
        partial void OnProvinceChanging(string value);
        partial void OnProvinceChanged();
        /// <summary>
        /// 架构中不存在属性 City 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this.ReportPropertyChanging("City");
                this._City = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("City");
                this.OnCityChanged();
            }
        }
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// 架构中不存在属性 Area 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Area
        {
            get
            {
                return this._Area;
            }
            set
            {
                this.OnAreaChanging(value);
                this.ReportPropertyChanging("Area");
                this._Area = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Area");
                this.OnAreaChanged();
            }
        }
        private string _Area;
        partial void OnAreaChanging(string value);
        partial void OnAreaChanged();
        /// <summary>
        /// 架构中不存在属性 Address 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this.ReportPropertyChanging("Address");
                this._Address = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Address");
                this.OnAddressChanged();
            }
        }
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// 架构中不存在属性 Tel 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel
        {
            get
            {
                return this._Tel;
            }
            set
            {
                this.OnTelChanging(value);
                this.ReportPropertyChanging("Tel");
                this._Tel = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Tel");
                this.OnTelChanged();
            }
        }
        private string _Tel;
        partial void OnTelChanging(string value);
        partial void OnTelChanged();
    }
    /// <summary>
    /// 架构中不存在 AladingWebModel.Update 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="AladingWebModel", Name="Update")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Update : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 Update 对象。
        /// </summary>
        /// <param name="id">Id 的初始值。</param>
        /// <param name="componentCode">ComponentCode 的初始值。</param>
        /// <param name="componentName">ComponentName 的初始值。</param>
        /// <param name="serverPath">ServerPath 的初始值。</param>
        /// <param name="serverFileName">ServerFileName 的初始值。</param>
        /// <param name="clientPath">ClientPath 的初始值。</param>
        /// <param name="clientFileName">ClientFileName 的初始值。</param>
        /// <param name="downloadName">DownloadName 的初始值。</param>
        /// <param name="version">Version 的初始值。</param>
        /// <param name="updatedTime">UpdatedTime 的初始值。</param>
        public static Update CreateUpdate(int id, string componentCode, string componentName, string serverPath, string serverFileName, string clientPath, string clientFileName, string downloadName, string version, global::System.DateTime updatedTime)
        {
            Update update = new Update();
            update.Id = id;
            update.ComponentCode = componentCode;
            update.ComponentName = componentName;
            update.ServerPath = serverPath;
            update.ServerFileName = serverFileName;
            update.ClientPath = clientPath;
            update.ClientFileName = clientFileName;
            update.DownloadName = downloadName;
            update.Version = version;
            update.UpdatedTime = updatedTime;
            return update;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 ComponentCode 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ComponentCode
        {
            get
            {
                return this._ComponentCode;
            }
            set
            {
                this.OnComponentCodeChanging(value);
                this.ReportPropertyChanging("ComponentCode");
                this._ComponentCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ComponentCode");
                this.OnComponentCodeChanged();
            }
        }
        private string _ComponentCode;
        partial void OnComponentCodeChanging(string value);
        partial void OnComponentCodeChanged();
        /// <summary>
        /// 架构中不存在属性 ComponentName 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ComponentName
        {
            get
            {
                return this._ComponentName;
            }
            set
            {
                this.OnComponentNameChanging(value);
                this.ReportPropertyChanging("ComponentName");
                this._ComponentName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ComponentName");
                this.OnComponentNameChanged();
            }
        }
        private string _ComponentName;
        partial void OnComponentNameChanging(string value);
        partial void OnComponentNameChanged();
        /// <summary>
        /// 架构中不存在属性 ServerPath 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerPath
        {
            get
            {
                return this._ServerPath;
            }
            set
            {
                this.OnServerPathChanging(value);
                this.ReportPropertyChanging("ServerPath");
                this._ServerPath = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ServerPath");
                this.OnServerPathChanged();
            }
        }
        private string _ServerPath;
        partial void OnServerPathChanging(string value);
        partial void OnServerPathChanged();
        /// <summary>
        /// 架构中不存在属性 ServerFileName 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerFileName
        {
            get
            {
                return this._ServerFileName;
            }
            set
            {
                this.OnServerFileNameChanging(value);
                this.ReportPropertyChanging("ServerFileName");
                this._ServerFileName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ServerFileName");
                this.OnServerFileNameChanged();
            }
        }
        private string _ServerFileName;
        partial void OnServerFileNameChanging(string value);
        partial void OnServerFileNameChanged();
        /// <summary>
        /// 架构中不存在属性 ClientPath 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientPath
        {
            get
            {
                return this._ClientPath;
            }
            set
            {
                this.OnClientPathChanging(value);
                this.ReportPropertyChanging("ClientPath");
                this._ClientPath = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ClientPath");
                this.OnClientPathChanged();
            }
        }
        private string _ClientPath;
        partial void OnClientPathChanging(string value);
        partial void OnClientPathChanged();
        /// <summary>
        /// 架构中不存在属性 ClientFileName 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientFileName
        {
            get
            {
                return this._ClientFileName;
            }
            set
            {
                this.OnClientFileNameChanging(value);
                this.ReportPropertyChanging("ClientFileName");
                this._ClientFileName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ClientFileName");
                this.OnClientFileNameChanged();
            }
        }
        private string _ClientFileName;
        partial void OnClientFileNameChanging(string value);
        partial void OnClientFileNameChanged();
        /// <summary>
        /// 架构中不存在属性 DownloadName 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DownloadName
        {
            get
            {
                return this._DownloadName;
            }
            set
            {
                this.OnDownloadNameChanging(value);
                this.ReportPropertyChanging("DownloadName");
                this._DownloadName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("DownloadName");
                this.OnDownloadNameChanged();
            }
        }
        private string _DownloadName;
        partial void OnDownloadNameChanging(string value);
        partial void OnDownloadNameChanged();
        /// <summary>
        /// 架构中不存在属性 Version 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this.ReportPropertyChanging("Version");
                this._Version = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Version");
                this.OnVersionChanged();
            }
        }
        private string _Version;
        partial void OnVersionChanging(string value);
        partial void OnVersionChanged();
        /// <summary>
        /// 架构中不存在属性 UpdatedTime 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime UpdatedTime
        {
            get
            {
                return this._UpdatedTime;
            }
            set
            {
                this.OnUpdatedTimeChanging(value);
                this.ReportPropertyChanging("UpdatedTime");
                this._UpdatedTime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UpdatedTime");
                this.OnUpdatedTimeChanged();
            }
        }
        private global::System.DateTime _UpdatedTime;
        partial void OnUpdatedTimeChanging(global::System.DateTime value);
        partial void OnUpdatedTimeChanged();
    }
    /// <summary>
    /// 架构中不存在 AladingWebModel.User 的注释。
    /// </summary>
    /// <KeyProperties>
    /// UserID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="AladingWebModel", Name="User")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class User : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 User 对象。
        /// </summary>
        /// <param name="userID">UserID 的初始值。</param>
        /// <param name="userCode">UserCode 的初始值。</param>
        /// <param name="userName">UserName 的初始值。</param>
        /// <param name="account">Account 的初始值。</param>
        /// <param name="password">Password 的初始值。</param>
        /// <param name="maxUser">MaxUser 的初始值。</param>
        /// <param name="hasUser">HasUser 的初始值。</param>
        /// <param name="maxShop">MaxShop 的初始值。</param>
        /// <param name="hasShop">HasShop 的初始值。</param>
        /// <param name="firstRun">FirstRun 的初始值。</param>
        /// <param name="approve">Approve 的初始值。</param>
        public static User CreateUser(int userID, string userCode, string userName, string account, string password, int maxUser, int hasUser, int maxShop, int hasShop, bool firstRun, bool approve)
        {
            User user = new User();
            user.UserID = userID;
            user.UserCode = userCode;
            user.UserName = userName;
            user.Account = account;
            user.Password = password;
            user.MaxUser = maxUser;
            user.HasUser = hasUser;
            user.MaxShop = maxShop;
            user.HasShop = hasShop;
            user.FirstRun = firstRun;
            user.Approve = approve;
            return user;
        }
        /// <summary>
        /// 架构中不存在属性 UserID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID
        {
            get
            {
                return this._UserID;
            }
            set
            {
                this.OnUserIDChanging(value);
                this.ReportPropertyChanging("UserID");
                this._UserID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UserID");
                this.OnUserIDChanged();
            }
        }
        private int _UserID;
        partial void OnUserIDChanging(int value);
        partial void OnUserIDChanged();
        /// <summary>
        /// 架构中不存在属性 UserCode 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UserCode
        {
            get
            {
                return this._UserCode;
            }
            set
            {
                this.OnUserCodeChanging(value);
                this.ReportPropertyChanging("UserCode");
                this._UserCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("UserCode");
                this.OnUserCodeChanged();
            }
        }
        private string _UserCode;
        partial void OnUserCodeChanging(string value);
        partial void OnUserCodeChanged();
        /// <summary>
        /// 架构中不存在属性 UserName 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this.ReportPropertyChanging("UserName");
                this._UserName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("UserName");
                this.OnUserNameChanged();
            }
        }
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// 架构中不存在属性 Account 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Account
        {
            get
            {
                return this._Account;
            }
            set
            {
                this.OnAccountChanging(value);
                this.ReportPropertyChanging("Account");
                this._Account = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Account");
                this.OnAccountChanged();
            }
        }
        private string _Account;
        partial void OnAccountChanging(string value);
        partial void OnAccountChanged();
        /// <summary>
        /// 架构中不存在属性 Password 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this.ReportPropertyChanging("Password");
                this._Password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Password");
                this.OnPasswordChanged();
            }
        }
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// 架构中不存在属性 Tel 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel
        {
            get
            {
                return this._Tel;
            }
            set
            {
                this.OnTelChanging(value);
                this.ReportPropertyChanging("Tel");
                this._Tel = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Tel");
                this.OnTelChanged();
            }
        }
        private string _Tel;
        partial void OnTelChanging(string value);
        partial void OnTelChanged();
        /// <summary>
        /// 架构中不存在属性 Mobile 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile
        {
            get
            {
                return this._Mobile;
            }
            set
            {
                this.OnMobileChanging(value);
                this.ReportPropertyChanging("Mobile");
                this._Mobile = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Mobile");
                this.OnMobileChanged();
            }
        }
        private string _Mobile;
        partial void OnMobileChanging(string value);
        partial void OnMobileChanged();
        /// <summary>
        /// 架构中不存在属性 Company 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Company
        {
            get
            {
                return this._Company;
            }
            set
            {
                this.OnCompanyChanging(value);
                this.ReportPropertyChanging("Company");
                this._Company = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Company");
                this.OnCompanyChanged();
            }
        }
        private string _Company;
        partial void OnCompanyChanging(string value);
        partial void OnCompanyChanged();
        /// <summary>
        /// 架构中不存在属性 Address 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this.ReportPropertyChanging("Address");
                this._Address = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Address");
                this.OnAddressChanged();
            }
        }
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// 架构中不存在属性 MaxUser 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxUser
        {
            get
            {
                return this._MaxUser;
            }
            set
            {
                this.OnMaxUserChanging(value);
                this.ReportPropertyChanging("MaxUser");
                this._MaxUser = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MaxUser");
                this.OnMaxUserChanged();
            }
        }
        private int _MaxUser;
        partial void OnMaxUserChanging(int value);
        partial void OnMaxUserChanged();
        /// <summary>
        /// 架构中不存在属性 HasUser 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int HasUser
        {
            get
            {
                return this._HasUser;
            }
            set
            {
                this.OnHasUserChanging(value);
                this.ReportPropertyChanging("HasUser");
                this._HasUser = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("HasUser");
                this.OnHasUserChanged();
            }
        }
        private int _HasUser;
        partial void OnHasUserChanging(int value);
        partial void OnHasUserChanged();
        /// <summary>
        /// 架构中不存在属性 MaxShop 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxShop
        {
            get
            {
                return this._MaxShop;
            }
            set
            {
                this.OnMaxShopChanging(value);
                this.ReportPropertyChanging("MaxShop");
                this._MaxShop = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MaxShop");
                this.OnMaxShopChanged();
            }
        }
        private int _MaxShop;
        partial void OnMaxShopChanging(int value);
        partial void OnMaxShopChanged();
        /// <summary>
        /// 架构中不存在属性 HasShop 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int HasShop
        {
            get
            {
                return this._HasShop;
            }
            set
            {
                this.OnHasShopChanging(value);
                this.ReportPropertyChanging("HasShop");
                this._HasShop = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("HasShop");
                this.OnHasShopChanged();
            }
        }
        private int _HasShop;
        partial void OnHasShopChanging(int value);
        partial void OnHasShopChanged();
        /// <summary>
        /// 架构中不存在属性 FirstRun 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool FirstRun
        {
            get
            {
                return this._FirstRun;
            }
            set
            {
                this.OnFirstRunChanging(value);
                this.ReportPropertyChanging("FirstRun");
                this._FirstRun = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FirstRun");
                this.OnFirstRunChanged();
            }
        }
        private bool _FirstRun;
        partial void OnFirstRunChanging(bool value);
        partial void OnFirstRunChanged();
        /// <summary>
        /// 架构中不存在属性 Approve 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool Approve
        {
            get
            {
                return this._Approve;
            }
            set
            {
                this.OnApproveChanging(value);
                this.ReportPropertyChanging("Approve");
                this._Approve = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Approve");
                this.OnApproveChanged();
            }
        }
        private bool _Approve;
        partial void OnApproveChanging(bool value);
        partial void OnApproveChanged();
    }
    /// <summary>
    /// 架构中不存在 AladingWebModel.Version 的注释。
    /// </summary>
    /// <KeyProperties>
    /// VersionID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="AladingWebModel", Name="Version")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Version : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 Version 对象。
        /// </summary>
        /// <param name="versionID">VersionID 的初始值。</param>
        /// <param name="versionCode">VersionCode 的初始值。</param>
        /// <param name="versionType">VersionType 的初始值。</param>
        /// <param name="remark">Remark 的初始值。</param>
        /// <param name="publishTime">PublishTime 的初始值。</param>
        public static Version CreateVersion(long versionID, string versionCode, string versionType, string remark, global::System.DateTime publishTime)
        {
            Version version = new Version();
            version.VersionID = versionID;
            version.VersionCode = versionCode;
            version.VersionType = versionType;
            version.Remark = remark;
            version.PublishTime = publishTime;
            return version;
        }
        /// <summary>
        /// 架构中不存在属性 VersionID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long VersionID
        {
            get
            {
                return this._VersionID;
            }
            set
            {
                this.OnVersionIDChanging(value);
                this.ReportPropertyChanging("VersionID");
                this._VersionID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("VersionID");
                this.OnVersionIDChanged();
            }
        }
        private long _VersionID;
        partial void OnVersionIDChanging(long value);
        partial void OnVersionIDChanged();
        /// <summary>
        /// 架构中不存在属性 VersionCode 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string VersionCode
        {
            get
            {
                return this._VersionCode;
            }
            set
            {
                this.OnVersionCodeChanging(value);
                this.ReportPropertyChanging("VersionCode");
                this._VersionCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("VersionCode");
                this.OnVersionCodeChanged();
            }
        }
        private string _VersionCode;
        partial void OnVersionCodeChanging(string value);
        partial void OnVersionCodeChanged();
        /// <summary>
        /// 架构中不存在属性 VersionType 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string VersionType
        {
            get
            {
                return this._VersionType;
            }
            set
            {
                this.OnVersionTypeChanging(value);
                this.ReportPropertyChanging("VersionType");
                this._VersionType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("VersionType");
                this.OnVersionTypeChanged();
            }
        }
        private string _VersionType;
        partial void OnVersionTypeChanging(string value);
        partial void OnVersionTypeChanged();
        /// <summary>
        /// 架构中不存在属性 Remark 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark
        {
            get
            {
                return this._Remark;
            }
            set
            {
                this.OnRemarkChanging(value);
                this.ReportPropertyChanging("Remark");
                this._Remark = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Remark");
                this.OnRemarkChanged();
            }
        }
        private string _Remark;
        partial void OnRemarkChanging(string value);
        partial void OnRemarkChanged();
        /// <summary>
        /// 架构中不存在属性 PublishTime 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime PublishTime
        {
            get
            {
                return this._PublishTime;
            }
            set
            {
                this.OnPublishTimeChanging(value);
                this.ReportPropertyChanging("PublishTime");
                this._PublishTime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PublishTime");
                this.OnPublishTimeChanged();
            }
        }
        private global::System.DateTime _PublishTime;
        partial void OnPublishTimeChanging(global::System.DateTime value);
        partial void OnPublishTimeChanged();
        /// <summary>
        /// 架构中不存在属性 Expand1 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Expand1
        {
            get
            {
                return this._Expand1;
            }
            set
            {
                this.OnExpand1Changing(value);
                this.ReportPropertyChanging("Expand1");
                this._Expand1 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Expand1");
                this.OnExpand1Changed();
            }
        }
        private string _Expand1;
        partial void OnExpand1Changing(string value);
        partial void OnExpand1Changed();
        /// <summary>
        /// 架构中不存在属性 Expand2 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Expand2
        {
            get
            {
                return this._Expand2;
            }
            set
            {
                this.OnExpand2Changing(value);
                this.ReportPropertyChanging("Expand2");
                this._Expand2 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Expand2");
                this.OnExpand2Changed();
            }
        }
        private string _Expand2;
        partial void OnExpand2Changing(string value);
        partial void OnExpand2Changed();
    }
}
